export const IMAP_PROVIDERS = {
  mailru: {
    key: 'mailru',
    titleKey: 'INBOX_MGMT.EMAIL_PROVIDERS.MAILRU.TITLE',
    descriptionKey: 'INBOX_MGMT.EMAIL_PROVIDERS.MAILRU.DESCRIPTION',
    label: 'Mail.ru',
    icon: 'i-woot-mail',
    imap: { address: 'imap.mail.ru', port: 993, ssl: true },
    smtp: {
      address: 'smtp.mail.ru',
      port: 465,
      sslTls: true,
      starttls: false,
      domain: 'mail.ru',
      authentication: 'login',
    },
  },
  yandex: {
    key: 'yandex',
    titleKey: 'INBOX_MGMT.EMAIL_PROVIDERS.YANDEX.TITLE',
    descriptionKey: 'INBOX_MGMT.EMAIL_PROVIDERS.YANDEX.DESCRIPTION',
    label: 'Yandex',
    icon: 'i-woot-mail',
    imap: { address: 'imap.yandex.ru', port: 993, ssl: true },
    smtp: {
      address: 'smtp.yandex.ru',
      port: 465,
      sslTls: true,
      starttls: false,
      domain: 'yandex.ru',
      authentication: 'login',
    },
  },
  rambler: {
    key: 'rambler',
    titleKey: 'INBOX_MGMT.EMAIL_PROVIDERS.RAMBLER.TITLE',
    descriptionKey: 'INBOX_MGMT.EMAIL_PROVIDERS.RAMBLER.DESCRIPTION',
    label: 'Rambler',
    icon: 'i-woot-mail',
    imap: { address: 'imap.rambler.ru', port: 993, ssl: true },
    smtp: {
      address: 'smtp.rambler.ru',
      port: 465,
      sslTls: true,
      starttls: false,
      domain: 'rambler.ru',
      authentication: 'login',
    },
  },
};
